"""This module has the systems available to scrape. If this module
needs to be updated, check the scripts/system.py file"""

SYSTEMS = [
    'Atari2600',
    'Atari5200',
    'NES',
    'SMS',
    'Atari7800',
    'TG16',
    'Genesis',
    'TGCD',
    'SNES',
    'SegaCD',
    '32X',
    'Saturn',
    'PS1',
    'N64',
    'Dreamcast',
    'PS2',
    'GameCube',
    'Xbox',
    'Xbox360',
    'PS3',
    'Wii',
    'WiiWare',
    'GB',
    'Lynx',
    'GG',
    'VB',
    'GBC',
    'GBA',
    'DS',
    'PSP',
]
